### ISSUE TITLE
Error with input value 

### ISSUE THREAD

**Issue by codemanish** [chsasank/Traffic-Sign-Classification.keras#6]
`Loaded images from X.h5
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_17 (Conv2D)           (None, 48, 48, 32)        896       
_________________________________________________________________
conv2d_18 (Conv2D)           (None, 46, 46, 32)        9248      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 23, 23, 32)        0         
_________________________________________________________________
dropout_9 (Dropout)          (None, 23, 23, 32)        0         
_________________________________________________________________
conv2d_19 (Conv2D)           (None, 23, 23, 64)        18496     
_________________________________________________________________
conv2d_20 (Conv2D)           (None, 21, 21, 64)        36928     
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 10, 10, 64)        0         
_________________________________________________________________
dropout_10 (Dropout)         (None, 10, 10, 64)        0         
_________________________________________________________________
conv2d_21 (Conv2D)           (None, 10, 10, 128)       73856     
_________________________________________________________________
conv2d_22 (Conv2D)           (None, 8, 8, 128)         147584    
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 4, 4, 128)         0         
_________________________________________________________________
dropout_11 (Dropout)         (None, 4, 4, 128)         0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 2048)              0         
_________________________________________________________________
dense_5 (Dense)              (None, 512)               1049088   
_________________________________________________________________
dropout_12 (Dropout)         (None, 512)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 43)                22059     
=================================================================
Total params: 1,358,155
Trainable params: 1,358,155
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):

  File "<ipython-input-6-78f0dd426f3b>", line 132, in <module>
    ModelCheckpoint('model.h5',save_best_only=True)]

  File "C:\Users\pandey\Anaconda3\lib\site-packages\keras\models.py", line 963, in fit
    validation_steps=validation_steps)

  File "C:\Users\pandey\Anaconda3\lib\site-packages\keras\engine\training.py", line 1630, in fit
    batch_size=batch_size)

  File "C:\Users\pandey\Anaconda3\lib\site-packages\keras\engine\training.py", line 1476, in _standardize_user_data
    exception_prefix='input')

  File "C:\Users\pandey\Anaconda3\lib\site-packages\keras\engine\training.py", line 113, in _standardize_input_data
    'with shape ' + str(data_shape))

ValueError: Error when checking input: expected conv2d_17_input to have 4 dimensions, but got array with shape (0, 1)`

**Comment by shanicky4ever** [comment]
same problem, have you clear that?

**Comment by codemanish** [comment]
No the problem is yet not cleared

**Comment by aalzooke** [comment]
Did you solve this error, Please share

**Comment by codemanish** [comment]
No brother i was unable to solve this

**Comment by aalzooke** [comment]
I really don't know how to solve it, I tried many times. 
Please let me know if you come up with a solution

**Comment by RuiChen520** [comment]
The same as yours.How to solve?
